apiVersion: v1
kind: Service
metadata:
  name: development
spec:
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 5000
  selector:
    app: development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: development
  template:
    metadata:
      labels:
        app: development
    spec:
      containers:
        - name: development
          image: gitlab.sdu.dk:5050/semester-project-e2021/team-03/template:latest
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: 700m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
      imagePullSecrets:
        - name: sdugitlab
